language: ruby
bundler_args: --without development
rvm:
  - jruby-1.6.8
  - jruby-1.7.4
  - jruby-head
env:
  - JRUBY_OPTS=--1.8
  - JRUBY_OPTS=--1.9
  - JRUBY_OPTS=--2.0
jdk:
  - openjdk7
  - openjdk6
matrix:
  exclude:
    - rvm: jruby-1.6.8
      jdk: openjdk6
      env: JRUBY_OPTS=--2.0
    - rvm: jruby-1.6.8
      jdk: openjdk7
      env: JRUBY_OPTS=--2.0
